'use client';
import { Bot, CheckCircle2, Languages, MapPin, MessageSquare, Navigation, Siren, X } from 'lucide-react';
import type { Alert, Incident } from '@/components/command/view';
import { useEffect, useState } from 'react';
import { RecommendationPanel } from '@/components/dispatch/RecommendationPanel';
import { getTrust } from '@/lib/command';
import type { IncidentTrust } from '@/types';
import { pageStrings } from '@/lib/pageStrings';
import { useLang } from '@/components/layout/LangProvider';

const TRUST_STYLE: Record<string, [string, string]> = {
 verified: ['var(--selected-bg)', 'var(--accent)'], corroborated: ['var(--soft-bg)', 'var(--blue)'],
 conflicting: ['var(--danger-soft)', 'var(--danger-text)'], unverified: ['var(--soft-bg)', 'var(--muted)'],
};

export function IncidentDrawer({incident,version,onEscalate,onResolve,onDispatched,onClose}:{incident:Incident|null;alerts:Alert[];version:number;onEscalate:()=>void;onResolve:()=>void;onDispatched:()=>void;onClose:()=>void}){
 const t=pageStrings(useLang().lang).drawer;
 const [tab,setTab]=useState<'overview'|'reports'>('overview');
 const [trust,setTrust]=useState<IncidentTrust|null>(null);
 const id=incident?Number(incident.id):null;
 useEffect(()=>{let alive=true;if(id!=null)getTrust(id).then(t=>{if(alive)setTrust(t)});return()=>{alive=false}},[id,version]);
 const trustShown=trust&&trust.incident_id===id?trust:null;
 if(!incident)return <div style={{height:'100%',display:'grid',placeItems:'center',color:'var(--muted)'}}><div style={{textAlign:'center'}}><MapPin size={30}/><div style={{marginTop:10,fontSize:12}}>{t.selectIncident}</div></div></div>;
 return <div className="scrollbar" style={{height:'100%',overflow:'auto'}}>
  <div style={{padding:'15px 16px 12px',borderBottom:'1px solid var(--line)',position:'sticky',top:0,background:'var(--panel)ee',backdropFilter:'blur(10px)',zIndex:3}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'start'}}><div><div style={{display:'flex',alignItems:'center',gap:7}}><span style={{fontSize:10,color:'var(--muted)'}}>{incident.code}</span><Badge text={incident.priority} danger={incident.priority==='P1'}/><Badge text={`SEV ${incident.severity}`} danger={incident.severity>=4}/><Badge text={incident.status.replace('_',' ')}/>{trustShown&&<span title={trustShown.conflicts.map(c=>`${c.field}: ${c.claims.map(x=>x.value).join(' vs ')}`).join('; ')||t.independentSources(trustShown.sources.unique_sources)} style={{fontSize:8,fontWeight:850,letterSpacing:.5,padding:'3px 5px',borderRadius:4,background:TRUST_STYLE[trustShown.verification]?.[0],color:TRUST_STYLE[trustShown.verification]?.[1]}}>{trustShown.verification.toUpperCase()}</span>}</div><h2 style={{fontSize:17,lineHeight:1.25,margin:'8px 0 4px'}}>{incident.title}</h2><div style={{display:'flex',alignItems:'center',gap:5,color:'var(--muted)',fontSize:10}}><MapPin size={12}/>{incident.address}</div></div><button onClick={onClose} aria-label={t.close} style={iconButton}><X size={16}/></button></div><div style={{display:'flex',gap:6,marginTop:13}}><Tab active={tab==='overview'} onClick={()=>setTab('overview')}>{t.overview}</Tab><Tab active={tab==='reports'} onClick={()=>setTab('reports')}>{t.reports} <span style={{opacity:.65}}>({incident.reportCount})</span></Tab></div></div>
  {tab==='reports'?<Reports incident={incident}/>:<>
   <section style={section}><SectionTitle icon={<Bot size={14}/>} title={t.aiSummary} tag={t.confidenceTag(Math.round(incident.confidence*100))}/>{incident.confidence<=0.4&&<div style={{display:'flex',gap:6,alignItems:'center',marginBottom:8,padding:'6px 8px',borderRadius:6,background:'var(--danger-soft)',color:'var(--danger-text)',fontSize:9,fontWeight:800}}><MapPin size={12}/> {t.locationUnverified}</div>}<p style={copy}>{incident.aiSummary||t.summarising}</p>{trustShown&&trustShown.conflicts.length>0&&<div style={{marginBottom:9,padding:9,borderRadius:7,border:'1px solid var(--danger-text)',fontSize:9.5,color:'var(--body-text)'}}><b style={{color:'var(--danger-text)'}}>{t.reportsDisagree}</b> {trustShown.conflicts.map(c=>`${c.field.replace('_',' ')}: ${c.claims.map(x=>`${x.value} (${x.source})`).join(' vs ')}`).join(' · ')}</div>}<div style={{padding:10,borderRadius:7,background:'var(--soft-bg)',border:'1px solid var(--line-strong)',fontSize:10,color:'var(--body-text)'}}><b style={{color:'var(--text)'}}>{t.reasoning}</b> {incident.reasoning}</div><div style={{marginTop:10}}><div style={{display:'flex',justifyContent:'space-between',fontSize:9,color:'var(--muted)',marginBottom:5}}><span>{t.modelConfidence}</span><b style={{color:'var(--accent)'}}>{Math.round(incident.confidence*100)}%</b></div><div style={{height:5,borderRadius:4,background:'var(--line-strong)',overflow:'hidden'}}><div style={{width:`${incident.confidence*100}%`,height:'100%',background:'var(--accent)'}}/></div></div></section>
   <section style={section}><SectionTitle icon={<CheckCircle2 size={14}/>} title={t.recommendedActions}/><div>{incident.actions.map((x,i)=><div key={x} style={{display:'flex',gap:9,alignItems:'center',padding:'7px 0',borderBottom:i<incident.actions.length-1?'1px solid var(--line)':'none',fontSize:10,color:'var(--body-text)'}}><span style={{width:17,height:17,borderRadius:4,border:'1px solid var(--line-strong)',display:'grid',placeItems:'center',fontSize:8,color:'var(--accent)'}}>{i+1}</span>{x}</div>)}</div></section>
   <section style={section}><SectionTitle icon={<Navigation size={14}/>} title={t.dispatchRecommendations}/><RecommendationPanel key={incident.id} incidentId={Number(incident.id)} version={version} dispatched={['dispatched','on_scene','resolved'].includes(incident.status)} onDispatched={onDispatched}/></section>
   <section style={section}><SectionTitle icon={<MessageSquare size={14}/>} title={t.activityTimeline}/><Timeline incident={incident} t={t}/></section>
   <section style={{...section,borderBottom:0}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7}}><button onClick={onResolve} disabled={incident.status==='resolved'} style={{...actionBtn('var(--action-bg)','var(--accent)'),opacity:incident.status==='resolved'?.5:1}}><CheckCircle2 size={13}/> {incident.status==='resolved'?t.resolved:t.resolve}</button><button onClick={onEscalate} disabled={incident.status==='escalated'} style={{...actionBtn('#4a1d1d','#b91c1c'),opacity:incident.status==='escalated'?.5:1}}><Siren size={13}/> {incident.status==='escalated'?t.escalated:t.escalate}</button></div></section>
  </>}
 </div>
}
function Badge({text,danger=false}:{text:string;danger?:boolean}){return <span style={{fontSize:8,fontWeight:850,letterSpacing:.5,padding:'3px 5px',borderRadius:4,background:danger?'var(--danger-soft)':'var(--soft-bg)',color:danger?'var(--danger-text)':'#9aada6'}}>{text}</span>}
function Tab({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} style={{padding:'6px 8px',border:0,borderBottom:active?'2px solid var(--accent)':'2px solid transparent',background:'transparent',color:active?'var(--text)':'var(--muted)',fontSize:9,fontWeight:800}}>{children}</button>}
function SectionTitle({icon,title,tag}:{icon:React.ReactNode;title:string;tag?:string}){return <div style={{display:'flex',alignItems:'center',gap:7,marginBottom:10,color:'var(--body-text)'}}><span style={{color:'var(--accent)'}}>{icon}</span><b style={{fontSize:9,letterSpacing:1}}>{title}</b>{tag&&<span style={{marginLeft:'auto',fontSize:8,color:'var(--accent)'}}>{tag}</span>}</div>}
const section:React.CSSProperties={padding:'14px 16px',borderBottom:'1px solid var(--line)'};const copy:React.CSSProperties={fontSize:10.5,lineHeight:1.55,color:'var(--body-text)',margin:'0 0 9px'};const iconButton:React.CSSProperties={width:29,height:29,borderRadius:6,border:'1px solid var(--line-strong)',background:'var(--input)',color:'var(--muted)',display:'grid',placeItems:'center'};const actionBtn=(bg:string,color:string):React.CSSProperties=>({height:33,borderRadius:6,border:'1px solid var(--line-strong)',background:bg,color,display:'flex',justifyContent:'center',alignItems:'center',gap:6,fontSize:9,fontWeight:850});
function Reports({incident}:{incident:Incident}){return <section style={section}>{incident.reports.map(r=><div key={r.id} style={{padding:'11px 0',borderBottom:'1px solid var(--line)'}}><div style={{display:'flex',alignItems:'center',gap:7}}><span style={{fontSize:8,padding:'3px 5px',borderRadius:3,background:'var(--soft-bg)',color:'var(--accent)'}}>{r.source.toUpperCase()}</span><Languages size={11} color="var(--muted)"/><span style={{fontSize:9,color:'var(--muted)'}}>{r.lang}</span><span style={{marginLeft:'auto',fontSize:9,color:'var(--muted)'}}>{r.time}</span></div><div style={{fontSize:10,color:'var(--body-text)',lineHeight:1.45,marginTop:7}}>{r.text}</div></div>)}</section>}
function Timeline({incident,t}:{incident:Incident;t:ReturnType<typeof pageStrings>['drawer']}){return <div style={{borderLeft:'1px solid var(--line-strong)',marginLeft:5,paddingLeft:13}}>{[[t.reportReceived,t.firstOf(incident.reportCount),incident.createdAt],[t.aiTriage,t.triageDetail(incident.type.replace('_',' '),incident.severity,incident.priority),incident.createdAt],[t.deduplication,t.mergedInto(incident.reportCount,incident.code),incident.reports[0]?.time??''],[t.currentState,incident.status.replace('_',' '),t.now]].map(([a,b,c],i)=><div key={a} style={{position:'relative',paddingBottom:i<3?13:0}}><span style={{position:'absolute',left:-18,top:1,width:8,height:8,borderRadius:'50%',background:i===3?'var(--accent)':'var(--line-strong)',border:'2px solid var(--panel)'}}/><div style={{fontSize:9,fontWeight:800,color:'var(--body-text)'}}>{a}</div><div style={{fontSize:9,color:'var(--muted)',marginTop:2}}>{b} · {c}</div></div>)}</div>}
