'use client';
import { useMemo, useState } from 'react';
import { ChevronDown, Filter, Radio, Waves, Flame, HeartPulse, Car, Factory, Building2 } from 'lucide-react';
import type { Incident, IncidentType } from '@/components/command/view';
const icon=(t:IncidentType)=>t==='flood'?<Waves size={15}/>:t==='fire'?<Flame size={15}/>:t==='medical'?<HeartPulse size={15}/>:t==='road_accident'?<Car size={15}/>:t==='industrial'?<Factory size={15}/>:<Building2 size={15}/>;
export function IncidentQueue({incidents,selectedId,onSelect}:{incidents:Incident[];selectedId:string|null;onSelect:(i:Incident)=>void}){
 const [type,setType]=useState('all'); const [status,setStatus]=useState('all'); const [sev,setSev]=useState('all');
 const types=useMemo(()=>Array.from(new Set(incidents.map(i=>i.type))),[incidents]);
 const filtered=incidents.filter(i=>(type==='all'||i.type===type)&&(status==='all'||i.status===status)&&(sev==='all'||String(i.severity)===sev)).sort((a,b)=>a.priority.localeCompare(b.priority)||a.createdAt.localeCompare(b.createdAt));
 return <div style={{height:'100%',display:'grid',gridTemplateRows:'82px 88px 1fr',minHeight:0}}>
  <div style={{padding:'14px 14px 10px',borderBottom:'1px solid var(--line)'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><div><div style={{fontSize:13,fontWeight:850}}>INCIDENT QUEUE</div><div style={{fontSize:9,color:'var(--muted)',marginTop:3,letterSpacing:1}}>{filtered.length} ACTIVE SIGNALS</div></div><span style={{display:'flex',gap:5,alignItems:'center',fontSize:9,color:'var(--accent)'}}><Radio size={12}/> LIVE</span></div></div>
  <div style={{padding:10,borderBottom:'1px solid var(--line)'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:6}}><Select value={type} onChange={setType} options={['all',...types]} label="TYPE"/><Select value={status} onChange={setStatus} options={['all','new','triaged','dispatched','on_scene','escalated']} label="STATUS"/><Select value={sev} onChange={setSev} options={['all','5','4','3','2','1']} label="SEV"/></div><div style={{display:'flex',alignItems:'center',gap:5,marginTop:8,color:'var(--muted)',fontSize:9}}><Filter size={12}/> SORT: <b style={{color:'var(--body-text)'}}>PRIORITY → AGE</b></div></div>
  <div className="scrollbar" style={{overflow:'auto',padding:'7px 8px'}}>{filtered.map(i=><button key={i.id} onClick={()=>onSelect(i)} style={{width:'100%',textAlign:'left',display:'grid',gridTemplateColumns:'34px 1fr auto',gap:9,padding:'11px 9px',marginBottom:4,borderRadius:7,border:i.id===selectedId?'1px solid var(--accent-border)':'1px solid transparent',background:i.id===selectedId?'var(--selected-bg)':'transparent',color:'var(--text)'}}><div style={{width:30,height:30,borderRadius:7,display:'grid',placeItems:'center',background:`${sevColor(i.severity)}22`,color:sevColor(i.severity)}}>{icon(i.type)}</div><div style={{minWidth:0}}><div style={{display:'flex',alignItems:'center',gap:6}}><b style={{fontSize:10}}>{i.code}</b><span style={{fontSize:8,padding:'2px 4px',borderRadius:3,background:i.priority==='P1'?'var(--danger-soft)':'var(--soft-bg)',color:i.priority==='P1'?'var(--danger-text)':'var(--body-text)'}}>{i.priority}</span></div><div style={{fontSize:11,fontWeight:700,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis',marginTop:3}}>{i.title}</div><div style={{fontSize:9,color:'var(--muted)',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis',marginTop:3}}>{i.address}</div></div><div style={{textAlign:'right'}}><div style={{fontSize:9,color:'var(--muted)'}}>{i.createdAt}</div><div style={{marginTop:8,fontSize:9,color:'var(--body-text)'}}>{i.reportCount} rpt</div></div></button>)}</div>
 </div>
}
function Select({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <div style={{position:'relative'}}><select value={value} onChange={e=>onChange(e.target.value)} style={{appearance:'none',width:'100%',height:28,borderRadius:5,border:'1px solid var(--line-strong)',background:'var(--input)',color:'var(--muted)',fontSize:9,padding:'0 18px 0 7px',outline:'none'}}>{options.map(o=><option key={o} value={o}>{o==='all'?label:o.replace('_',' ')}</option>)}</select><ChevronDown size={10} style={{position:'absolute',right:5,top:9,color:'var(--muted)',pointerEvents:'none'}}/></div>}
function sevColor(n:number){return ['#22c55e','#84cc16','#f59e0b','#f97316','#ef4444'][n-1]||'#64748b'}
