"use client";

/**
 * What the citizen sees after submitting.
 *
 * Two things are kept strictly apart:
 *   - their report, shown verbatim in the language they wrote it
 *   - the system's operational interpretation, clearly labelled as such
 *
 * The AI's reading never replaces or overwrites the citizen's words, and the
 * wording never claims the system has confirmed an emergency — only that it
 * has classified a report and passed it to an operator.
 */

import type { Lang, ReportCreateResponse, ReportStage } from "@/types";
import { REPORT_STAGES, TYPE_LABEL_I18N, UI_STRINGS } from "@/lib/constants";
import { Panel } from "@/components/layout/primitives";
import { SafetyAdvice } from "@/components/report/SafetyAdvice";
import {
  ConfidenceMeter,
  HazardList,
  SeverityBadge,
  VerificationBadge,
} from "@/components/layout/trust";

const STAGE_ORDER: ReportStage[] = [
  "received",
  "ai_triage",
  "evidence_check",
  "incident_linked",
  "operational_review",
];

export function ReportReceipt({
  result,
  lang,
  submittedAt,
  originalText,
  onNewReport,
}: {
  result: ReportCreateResponse;
  lang: Lang;
  submittedAt: string;
  /** The citizen's text exactly as typed — not re-read from the response. */
  originalText: string;
  onNewReport: () => void;
}) {
  const t = UI_STRINGS[lang];
  const { report, incident, classification, merged } = result;

  // The pipeline has run through linking; a human has not yet reviewed it.
  const currentStage: ReportStage = "incident_linked";
  const currentIndex = STAGE_ORDER.indexOf(currentStage);

  return (
    <div className="space-y-4">
      <div
        className="border-l-4 px-3 py-3"
        style={{ borderColor: "var(--ok)", background: "var(--ok-bg)" }}
      >
        <h1 className="text-lg font-bold">{t.received}</h1>
        <dl className="mt-2 grid grid-cols-2 gap-x-4 gap-y-1 text-sm">
          <dt className="text-xs uppercase tracking-wide text-[var(--muted)]">{t.reportId}</dt>
          <dt className="text-xs uppercase tracking-wide text-[var(--muted)]">{t.submittedAt}</dt>
          <dd className="mono font-semibold">#{report.id}</dd>
          <dd className="mono">{formatTime(submittedAt)}</dd>
        </dl>
      </div>

      {/* Safety first: what to do until help arrives, in the citizen's language. */}
      <SafetyAdvice type={classification.type} hazards={classification.hazards} lang={lang} />

      {/* Progress — each stage named, with the reached ones marked. */}
      <Panel title="Status">
        <ol className="divide-y divide-[var(--border)]">
          {REPORT_STAGES.map((stage, index) => {
            const done = index <= currentIndex;
            const isCurrent = index === currentIndex;
            return (
              <li key={stage.id} className="flex items-center gap-3 px-3 py-2">
                <span
                  aria-hidden
                  className="inline-flex size-5 shrink-0 items-center justify-center rounded-full text-[11px] font-bold"
                  style={{
                    background: done ? "var(--ok)" : "var(--surface-2)",
                    color: done ? "#052e16" : "var(--muted)",
                    border: done ? "none" : "1px solid var(--border-strong)",
                  }}
                >
                  {done ? "✓" : index + 1}
                </span>
                <span className={`text-sm ${isCurrent ? "font-semibold" : ""}`}>
                  {stage.id === "incident_linked"
                    ? merged
                      ? `Linked to existing incident ${incident.code}`
                      : `New incident ${incident.code} opened`
                    : stage.label}
                </span>
                {isCurrent && (
                  <span className="ml-auto text-xs uppercase tracking-wide text-[var(--muted)]">
                    Current
                  </span>
                )}
              </li>
            );
          })}
        </ol>
        <p className="border-t border-[var(--border)] px-3 py-2 text-xs text-[var(--muted)]">
          An operator reviews every report before any unit is sent. The system classifies and
          groups reports; it does not decide the response.
        </p>
      </Panel>

      {/* The citizen's own words, untouched. */}
      <Panel title={t.yourWords}>
        <blockquote
          lang={lang}
          className="px-3 py-3 text-base leading-relaxed whitespace-pre-wrap"
        >
          {originalText}
        </blockquote>
      </Panel>

      {/* The system's reading, clearly separated and labelled. */}
      <Panel
        title={t.operationalReading}
        subtitle="Generated by AI from your report, for the control room. Your report above is what gets reviewed."
      >
        <dl className="divide-y divide-[var(--border)]">
          <Row label="Type">
            {TYPE_LABEL_I18N[lang][classification.type]}
            <span className="ml-2 text-xs text-[var(--muted)]">
              ({classification.type.replace("_", " ")})
            </span>
          </Row>
          <Row label="Severity">
            <SeverityBadge severity={classification.severity} />
          </Row>
          <Row label="Location">
            <span className="mono text-sm">
              {report.address ??
                classification.location_text ??
                (report.lat !== null && report.lng !== null
                  ? `${report.lat.toFixed(5)}, ${report.lng.toFixed(5)}`
                  : "Not supplied — operator will call back")}
            </span>
          </Row>
          <Row label="Hazards">
            <HazardList hazards={classification.hazards} />
          </Row>
          <Row label="Verification">
            <VerificationBadge status={merged ? "corroborated" : "unverified"} />
            <p className="mt-1 text-xs text-[var(--muted)]">
              {merged
                ? "Other reports describe the same incident."
                : "Yours is the only report so far. Not yet corroborated."}
            </p>
          </Row>
          <Row label="AI confidence">
            <ConfidenceMeter confidence={classification.confidence} />
          </Row>
        </dl>
      </Panel>

      <button
        type="button"
        onClick={onNewReport}
        className="min-h-12 w-full border border-[var(--border-strong)] bg-[var(--surface)] px-3 font-semibold hover:bg-[var(--surface-2)]"
      >
        {t.newReport}
      </button>
    </div>
  );
}

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="px-3 py-2">
      <dt className="text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">
        {label}
      </dt>
      <dd className="mt-1">{children}</dd>
    </div>
  );
}

function formatTime(iso: string): string {
  const d = new Date(iso);
  return `${d.toLocaleDateString()} ${d.toTimeString().slice(0, 8)}`;
}
